### ISSUE TITLE
errors with fresh installation

### ISSUE THREAD

**Issue by atomGit** [bigin/Scriptor#17]
this was displayed after extracting the zip upon the first visit to /editor

```
Type | E_DEPRECATED
-- | --
Creation of dynamic property Imanager\CategoryMapper::$categories is deprecated
/srv/http/imanager/lib/CategoryMapper.php
```

php 8, apache, linux

was also displeased to see it uses 3rd party content from jsdeliver and google

**Comment by bigin** [comment]
Thanks. It looks like the issue is specific to PHP 8.2, even though PHP 8 was initially mentioned. PHP 8.1 should probably run without any issues.

Regarding the 3rd-party stuff from jsdelivr and google, you can set the paths yourself by editing template files under site/themes/basic/ and editor/theme/css/styles.css (for the admin). I'll be looking into a solution for this in the near future.
